### ISSUE TITLE
Aeroplane config

### ISSUE THREAD

**Issue by airship100** [cleanflight/cleanflight-configurator#204] opened 2015-06-01 15:37 UTC
Hi
is it possible to add a 2nd motor to aeroplane config to a allow diif thrust with yaw control.

thanks

**Comment by MauroMombelli** [comment] 2015-06-17 10:31
this should be asked to cleanflight, as this require a heavy rewrite of the plane logic. Look at src/flight/mixer.c to see how a plane "think"

**Comment by AustinSaintAubin** [comment] 2015-10-04 14:45
This is doable now with custom airplane config.
Solved in & Duplicate of #248

**Comment by skaman82** [comment] 2016-06-16 16:17
this seems to be already done, if not please reopen

**Closed by skaman82** 2016-06-16 16:17 UTC
