### ISSUE TITLE
Need setup wizard for motors/receivers settings

### ISSUE THREAD

**Issue by proggod** [cleanflight/cleanflight-configurator#349] opened 2016-02-28 20:07 UTC
Is there any issue with me creating some sort of a wizard, so it automatically sets up mmix settings, rxrange settings, midpoints, receiver types, etc?   Seems it would be a lot easier for someone to use cleanflight, if there was a simple wizard to do all these settings.  It took me a few days to master all these settings, when it could easily be done automatically?

Is the best place to talk to someone about getting up on the code base, irc?   If so who should I talk to?

**Comment by alanzanotto** [comment] 2016-03-01 04:04
this would be awesome

**Comment by proggod** [comment] 2016-03-01 05:41
I think I will start working on it tomorrow, if no one else has any objections, or any ideas how they think it should be done..

**Comment by skaman82** [comment] 2016-06-16 16:36
duplicate of: #98

**Closed** 2016-06-19 15:11 UTC
