### ISSUE TITLE
Sensors tab seems broken

### ISSUE THREAD

**Issue by skaman82** [cleanflight/cleanflight-configurator#255] opened 2015-10-15 10:58 UTC
I just noticed that the sensor tab is broken. Tested it with two different computers and two naze32 boards. When I connect the board and click on Sensors. It shows nothing. When I try clicking on other tabs it doesn't react. I can just klick disconnect or restart the app to get to the other tabs again. 
![bildschirmfoto 2015-10-15 um 12 53 49](https://cloud.githubusercontent.com/assets/11768024/10511852/79cb8756-733c-11e5-8085-be96fe380a7b.png)

**Comment by qfather** [comment] 2015-10-15 12:17
Can't reproduce this with 1.10 firmware or 1.11 build 2236 on a Naze32.

**Comment by HaukeRa** [comment] 2015-10-16 08:00
Have the same issue with 1.11 and the master branch of the configurator, the development branch works fine

**Comment by borisbstyle** [comment] 2015-10-16 11:47
I have the same issue on 1.10 and even on 1.11.

**Comment by borisbstyle** [comment] 2015-10-16 11:49
And indeed it works on dev version

**Comment by skaman82** [comment] 2015-10-16 12:06
Since 1.10 is released an the dev version of the configurator is not its not a solution to use the dev version.

**Comment by qfather** [comment] 2015-10-16 12:18
It is a prerequisite to use the dev version.  The very first line in the release info of the firmware states this.

**Comment by skaman82** [comment] 2015-10-16 12:23
@qfather yes you are right. IMO there should never be a CF version released without the full compatible version of configurator.

**Comment by nwenkel** [comment] 2015-10-17 10:34
Have had the same issue with the developer version. After reinstalling 0.66 the sensors tab works again.

**Comment by Rhyell** [comment] 2015-10-23 13:52
The issue lies in the sonars.js file. 

Line 17 reads 
SENSOR_DATA.sonar[i] = 0;

It should read 
SENSOR_DATA.sonar = 0;

**Comment by JohnOCFII** [comment] 2015-10-24 00:20
> The issue lies in the sensors.js file in the tabs folder.

Thanks.  With all the other Chrome related issues popping up lately, I had assumed this was related to the version 46 release of Chrome.  I guess not.  I've now pulled down a fresh version of the development configurator (a shame it isn't released yet) and the problem is gone.

**Comment by MauroMombelli** [comment] 2015-10-29 14:20
sensors.js:17 Uncaught TypeError: Cannot assign to read only property '0' of 0

**Comment by hydra** [comment] 2015-11-10 02:10
Unable to reproduce in development branch, closing.  Open a new issue if there's still problems.

**Closed by hydra** 2015-11-10 02:10 UTC
